<?php
/**
 * @file
 * search_thai.module integrates & improves Thai content searching
 * for core search module.
 */

/**
 * Define Thai unicode range classes
 *
 * Thai Unicode range 0E00-0E7F.
 * @see http://unicode.org/charts/PDF/U0E00.pdf
 *
 * Or simply use '\p{Thai}'
 * @see http://www.regular-expressions.info/unicode.html#script
 */
define('PREG_CLASS_TH', '\x{0E00}-\x{0E7F}');

/**
 * Thai tone-marks & some special characters can be omitted from search index.
 */
define('PREG_CLASS_TH_OMIT', '\x{0E2F}\x{0E3F}\x{0E45}-\x{0E4F}\x{0E5A}-\x{0E5B}');

/**
 * Implements hook_form_FORM_ID_alter().
 */
function search_thai_form_search_admin_settings_alter(&$form, &$form_state, $form_id) {

  // Add a checkbox to search admin settings form.
  $form['indexing_settings']['overlap_th'] = array(
    '#type' => 'checkbox',
    '#title' => t('Simple Thai handling'),
    '#default_value' => variable_get('overlap_th', TRUE),
    '#description' => t('Whether to apply a simple Thai tokenizer based on overlapping sequences. Turn this off if you want to use an external preprocessor for this instead. Does not affect other languages.')
  );

}

/**
 * Implements hook_search_preprocess().
 *
 * @note I use search_expand_cjk() to tokenize Thai texts the same way CJK handling does.
 * The better way to correctly split Thai words is to use external dictionaries
 * but that's not the purpose of this simple module (at the moment).
 * @see search_simplify()
 */
function search_thai_search_preprocess($text) {

  if (variable_get('overlap_th', TRUE)) {
	  $text = preg_replace('/[' . PREG_CLASS_TH_OMIT . ']+/u', '', $text);
		$text = preg_replace_callback('/[' . PREG_CLASS_TH . ']+/u', 'search_expand_th', $text);
  }
  return $text;
}

function search_expand_th($matches) {
  $min = variable_get('minimum_word_size', 3);
  $str = $matches[0];
  $length = mb_strlen($str);
  // If the text is shorter than the minimum word size, don't tokenize it.
  if ($length <= $min) {
    return ' ' . $str . ' ';
  }
  $tokens = ' ';
  // Build a FIFO queue of characters.
  $chars = array();
  for ($i = 0; $i < $length; $i++) {
    // Add the next character off the beginning of the string to the queue.
    $current = drupal_substr($str, 0, 1);
    $str = substr($str, strlen($current));
    $chars[] = $current;
    if ($i >= $min - 1) {
      // Make a token of $min characters, and add it to the token string.
      $tokens .= implode('', $chars) . ' ';
      // Shift out the first character in the queue.
      array_shift($chars);
    }
  }
  return $tokens;
}
