<?php
/**
 * @file
 * search_thai.module integrates & improves Thai contents searching
 * for Drupal core search module.
 *
 * Thai unicode range reference.
 * @see http://unicode.org/charts/PDF/U0E00.pdf
 */

// Thai unicode range is 0E00-0E7F or simply use \p{Thai}
define('PREG_CLASS_TH', '\x{0E00}-\x{0E7F}');

// Thai front vowel สระหน้า: เอ แอ โอ ใอ ไอ
define('PREG_CLASS_TH_VOWEL_FRONT', '\x{0E40}-\x{0E44}');

// Thai characters which can be used as word back boundary
// สระอะ (0E30), สระอำ (0E33), ไปยาลน้อย (0E2F), ไม้ยมก (0E46), การันต์ (0E4C) และอื่นๆ 
define('PREG_CLASS_TH_WORD_BACK_BOUNDARY', '\x{0E30}\x{0E33}\x{0E2F}\x{0E45}-\x{0E46}\x{0E4C}-\x{0E4F}\x{0E5A}-\x{0E5B}');

// Thai tone-marks & some special characters can be omitted from search index.
define('PREG_CLASS_TH_OMIT', '\x{0E47}-\x{0E4F}');

// Thai characters which can't be the begining of the words (not yet useful for the moment).
define('PREG_CLASS_TH_NOT_FIRST', '\x{0E2F}-\x{0E3A}\x{0E45}-\x{0E4F}\x{0E5A}-\x{0E5B}');

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add a checkbox to search admin settings form.
 */
function search_thai_form_search_admin_settings_alter(&$form, &$form_state, $form_id) {
  $form['indexing_settings']['overlap_th'] = array(
    '#type' => 'checkbox',
    '#title' => t('Simple Thai handling'),
    '#default_value' => variable_get('overlap_th', TRUE),
    '#description' => t('Whether to apply a simple Thai tokenizer based on overlapping sequences. Turn this off if you want to use an external preprocessor for this instead. Does not affect other languages.')
  );
}

/**
 * Implements hook_search_preprocess().
 *
 * Replace and filter out some Thai characters 
 * which can be use as word boundary with regular expression.
 *
 * @param $str
 *   $str is sequence of Thai characters,
 *   it can be anything from a single character to full sentence(s)
 *   because Thai writing system has no space between words
 *
 * @return
 *   Tokenized text which ready for search indexing.
 */
function search_thai_search_preprocess($str) {

  if (variable_get('overlap_th', TRUE)) {

    // Add space after back word boundary
    $str = preg_replace('/[' . PREG_CLASS_TH_WORD_BACK_BOUNDARY . ']+/u', '$0 ', $str);

    // Add space before front vowel
    $str = preg_replace('/[' . PREG_CLASS_TH_VOWEL_FRONT . ']+/u', ' $0', $str);

    // Remove unnecessary characters for indexing
    $str = preg_replace('/[' . PREG_CLASS_TH_OMIT . ']+/u', '', $str);

    // Tokenization
    $str = preg_replace_callback('/[' . PREG_CLASS_TH . ']+/u', 'search_expand_th', $str);

  }

  return $str;
}

/**
 * Splits Thai text into tokens.
 *
 * @param $matches
 *   $matches is an array of regular expression matches, 
 *   which means that $matches[0] contains the matched text 
 *   or a single string of Thai characters to tokenize.
 *
 * @return
 *   Tokenized text, starting and ending with a space character.
 *
 * @see search_expand_cjk() for example.
 */
function search_expand_th($matches) {

  $min = variable_get('minimum_word_size', 3);
  $str = $matches[0];
  $length = mb_strlen($str);

  // If the text is shorter than the minimum word size, don't tokenize it.
  if ($length <= $min) {
    return ' ' . $str . ' ';
  }

  $tokens = ' ';

  // Build a FIFO queue of characters.
  $chars = array();

  for ($i = 0; $i < $length; $i++) {
    // Add the next character off the beginning of the string to the queue.
    $current = drupal_substr($str, 0, 1);
    $str = substr($str, strlen($current));
    $chars[] = $current;

    // Filter out PREG_CLASS_TH_NOT_FIRST
    if ($i >= $min - 1) {
      // Make a token of $min characters, and add it to the token string.
      $tokens .= implode('', $chars) . ' ';
      // Shift out the first character in the queue.
      array_shift($chars);
    }
  }
  return $tokens;

}
