<?php
/**
 * @file
 * Install, update and uninstall functions for the search_thai module.
 */

/**
 * Implements hook_install().
 */
function search_thai_install() {

  // Set default variable as soon as install the module
  variable_set('overlap_th', 1);
  variable_set('minimum_word_size', 3);

  // Disable CJK handling for performance reason
  variable_set('overlap_cjk', 0);

}

/**
 * Implements hook_uninstall().
 */
function search_thai_uninstall() {
  variable_del('overlap_th');
}